version: '3'

services:
  web:
    build:
      context: ./
      dockerfile: ./docker/web/Dockerfile
    container_name: ptournament-web
    ports:
      - '80:80'
    volumes:
      - './:/app'
      - './docker/web/nginx/ptournament.conf:/etc/nginx/conf.d/ptournament.conf'
    links:
      - database
    networks:
      - ptournament-network

  database:
    image: mysql:5.7
    container_name: ptournament-database
    environment:
        MYSQL_DATABASE: 'ptournament'
        MYSQL_USER: 'ptournament'
        MYSQL_PASSWORD: 'ptournament'
        MYSQL_ROOT_PASSWORD: 'ptournament'
    ports:
        - '3306:3306'
    volumes:
        - mysql:/var/lib/mysql
    networks:
        - ptournament-network

volumes:
  mysql:

networks:
  ptournament-network:
    driver: bridge
