base_path: /

routes:
  match/result: [/api/match/result, PoolTournament\Application\Module\Match\Entrypoint\Http\Rest\IndexController::resultAction, [POST, PUT]]
  match/list: [/api/match/list, PoolTournament\Application\Module\Match\Entrypoint\Http\Rest\IndexController::listAction, GET]
  match/info: [/api/match/:id, PoolTournament\Application\Module\Match\Entrypoint\Http\Rest\IndexController::infoAction, GET]
  friend/ranking: [/api/friend/ranking, PoolTournament\Application\Module\Friend\Entrypoint\Http\Rest\IndexController::rankingAction, GET]
  friend/info: [/api/friend/:id, PoolTournament\Application\Module\Friend\Entrypoint\Http\Rest\IndexController::infoAction, GET]
  friend/matches: [/api/friend/:id/matches, PoolTournament\Application\Module\Friend\Entrypoint\Http\Rest\IndexController::matchesAction, GET]
