base_path: /

routes:
  homepage: [/, PoolTournament\Application\Module\Tournament\Entrypoint\IndexController::indexAction, GET]
  homepage/index: [/index, PoolTournament\Application\Module\Tournament\Entrypoint\IndexController::indexAction, GET]
  match: [/match/:id, PoolTournament\Application\Module\Match\Entrypoint\IndexController::indexAction, GET]
  friend: [/friend/:id, PoolTournament\Application\Module\Friend\Entrypoint\IndexController::indexAction, GET]
  match/result: [/match/result, PoolTournament\Application\Module\Match\Entrypoint\IndexController::resultAction, [POST, PUT]]