base_path: /

routes:
  homepage: [/, PoolTournament\App\Module\Tournament\Entrypoint\IndexController::indexAction, GET]
  php: [/php, PoolTournament\App\Module\Tournament\Entrypoint\IndexController::phpAction, GET]
  homepage/index: [/index, PoolTournament\App\Module\Tournament\Entrypoint\IndexController::indexAction, GET]
  match: [/match/:id, PoolTournament\App\Module\Match\Entrypoint\IndexController::indexAction, GET]
  friend: [/friend/:id, PoolTournament\App\Module\Friend\Entrypoint\IndexController::indexAction, GET]
  match/result: [/match/result, PoolTournament\App\Module\Match\Entrypoint\IndexController::resultAction, [POST, PUT]]